/**
 * Activity / audit action keys.
 */

export const ACTIVITY_ACTIONS = {
  LOGIN: "auth.login",
  LOGOUT: "auth.logout",
  LOGIN_FAILED: "auth.login_failed",
  PASSWORD_CHANGE: "auth.password_change",
  PASSWORD_RESET_REQUEST: "auth.password_reset_request",
  PASSWORD_RESET: "auth.password_reset",
  EMAIL_VERIFIED: "auth.email_verified",
  PROFILE_UPDATE: "profile.update",
  PROFILE_COMPLETE: "profile.complete",
  ROLE_CHANGE: "users.role_change",
  PERMISSION_CHANGE: "users.permission_change",
  USER_CREATED: "users.created",
  USER_DELETED: "users.deleted",
  STATUS_CHANGE: "users.status_change",
  SESSION_REVOKED: "auth.session_revoked",
  SETTINGS_UPDATE: "settings.update",
  FEATURE_FLAG_CHANGE: "settings.feature_flag",
  BRANDING_UPLOAD: "settings.branding_upload",
  // Courses / LMS
  COURSE_CREATED: "courses.created",
  COURSE_UPDATED: "courses.updated",
  COURSE_DELETED: "courses.deleted",
  COURSE_PUBLISHED: "courses.published",
  COURSE_UNPUBLISHED: "courses.unpublished",
  COURSE_ARCHIVED: "courses.archived",
  COURSE_DUPLICATED: "courses.duplicated",
  COURSE_BULK: "courses.bulk",
  MODULE_CREATED: "courses.module_created",
  MODULE_UPDATED: "courses.module_updated",
  MODULE_DELETED: "courses.module_deleted",
  LESSON_CREATED: "courses.lesson_created",
  LESSON_UPDATED: "courses.lesson_updated",
  LESSON_DELETED: "courses.lesson_deleted",
  RESOURCE_ADDED: "courses.resource_added",
  RESOURCE_REMOVED: "courses.resource_removed",
  ENROLLMENT_CREATED: "courses.enrollment_created",
  ENROLLMENT_UPDATED: "courses.enrollment_updated",
  ENROLLMENT_REMOVED: "courses.enrollment_removed",
  ENROLLMENT_BULK: "courses.enrollment_bulk",
  CATEGORY_CREATED: "courses.category_created",
  CATEGORY_UPDATED: "courses.category_updated",
  CATEGORY_DELETED: "courses.category_deleted",
  INSTRUCTOR_ASSIGNED: "courses.instructor_assigned",
  MEDIA_UPLOADED: "courses.media_uploaded",
  // Live classes / Zoom
  CLASS_CREATED: "classes.created",
  CLASS_UPDATED: "classes.updated",
  CLASS_DELETED: "classes.deleted",
  CLASS_CANCELLED: "classes.cancelled",
  CLASS_RESCHEDULED: "classes.rescheduled",
  CLASS_DUPLICATED: "classes.duplicated",
  CLASS_STARTED: "classes.started",
  ZOOM_MEETING_CREATED: "zoom.meeting_created",
  ZOOM_MEETING_UPDATED: "zoom.meeting_updated",
  ZOOM_MEETING_CANCELLED: "zoom.meeting_cancelled",
  ATTENDANCE_UPDATED: "classes.attendance_updated",
  REMINDER_QUEUED: "classes.reminder_queued",
  REMINDER_SENT: "classes.reminder_sent",
  RECORDING_REGISTERED: "classes.recording_registered",
  // Student learning
  LESSON_STARTED: "learning.lesson_started",
  LESSON_COMPLETED: "learning.lesson_completed",
  PROGRESS_UPDATED: "learning.progress_updated",
  NOTE_CREATED: "learning.note_created",
  NOTE_UPDATED: "learning.note_updated",
  NOTE_DELETED: "learning.note_deleted",
  BOOKMARK_ADDED: "learning.bookmark_added",
  BOOKMARK_REMOVED: "learning.bookmark_removed",
  FAVORITE_ADDED: "learning.favorite_added",
  FAVORITE_REMOVED: "learning.favorite_removed",
  GOAL_CREATED: "learning.goal_created",
  GOAL_UPDATED: "learning.goal_updated",
  STUDY_SESSION_CREATED: "learning.study_session_created",
  RESOURCE_DOWNLOADED: "learning.resource_downloaded",
  // Assessment / quizzes
  QUIZ_CREATED: "quizzes.created",
  QUIZ_UPDATED: "quizzes.updated",
  QUIZ_DELETED: "quizzes.deleted",
  QUIZ_PUBLISHED: "quizzes.published",
  QUIZ_UNPUBLISHED: "quizzes.unpublished",
  QUIZ_ARCHIVED: "quizzes.archived",
  QUIZ_DUPLICATED: "quizzes.duplicated",
  QUESTION_CREATED: "quizzes.question_created",
  QUESTION_UPDATED: "quizzes.question_updated",
  QUESTION_DELETED: "quizzes.question_deleted",
  QUESTION_IMPORTED: "quizzes.question_imported",
  ATTEMPT_STARTED: "quizzes.attempt_started",
  ATTEMPT_SAVED: "quizzes.attempt_saved",
  ATTEMPT_SUBMITTED: "quizzes.attempt_submitted",
  ATTEMPT_GRADED: "quizzes.attempt_graded",
  SUSPICIOUS_ACTIVITY: "quizzes.suspicious_activity",
} as const;

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[keyof typeof ACTIVITY_ACTIONS];
