/**
 * Activity / audit action keys.
 */

export const ACTIVITY_ACTIONS = {
  LOGIN: "auth.login",
  LOGOUT: "auth.logout",
  LOGIN_FAILED: "auth.login_failed",
  PASSWORD_CHANGE: "auth.password_change",
  PASSWORD_RESET_REQUEST: "auth.password_reset_request",
  PASSWORD_RESET: "auth.password_reset",
  EMAIL_VERIFIED: "auth.email_verified",
  PROFILE_UPDATE: "profile.update",
  PROFILE_COMPLETE: "profile.complete",
  ROLE_CHANGE: "users.role_change",
  PERMISSION_CHANGE: "users.permission_change",
  USER_CREATED: "users.created",
  USER_DELETED: "users.deleted",
  STATUS_CHANGE: "users.status_change",
  SESSION_REVOKED: "auth.session_revoked",
  SETTINGS_UPDATE: "settings.update",
  FEATURE_FLAG_CHANGE: "settings.feature_flag",
  BRANDING_UPLOAD: "settings.branding_upload",
  // Courses / LMS
  COURSE_CREATED: "courses.created",
  COURSE_UPDATED: "courses.updated",
  COURSE_DELETED: "courses.deleted",
  COURSE_PUBLISHED: "courses.published",
  COURSE_UNPUBLISHED: "courses.unpublished",
  COURSE_ARCHIVED: "courses.archived",
  COURSE_DUPLICATED: "courses.duplicated",
  COURSE_BULK: "courses.bulk",
  MODULE_CREATED: "courses.module_created",
  MODULE_UPDATED: "courses.module_updated",
  MODULE_DELETED: "courses.module_deleted",
  LESSON_CREATED: "courses.lesson_created",
  LESSON_UPDATED: "courses.lesson_updated",
  LESSON_DELETED: "courses.lesson_deleted",
  RESOURCE_ADDED: "courses.resource_added",
  RESOURCE_REMOVED: "courses.resource_removed",
  ENROLLMENT_CREATED: "courses.enrollment_created",
  ENROLLMENT_UPDATED: "courses.enrollment_updated",
  ENROLLMENT_REMOVED: "courses.enrollment_removed",
  ENROLLMENT_BULK: "courses.enrollment_bulk",
  CATEGORY_CREATED: "courses.category_created",
  CATEGORY_UPDATED: "courses.category_updated",
  CATEGORY_DELETED: "courses.category_deleted",
  INSTRUCTOR_ASSIGNED: "courses.instructor_assigned",
  MEDIA_UPLOADED: "courses.media_uploaded",
} as const;

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[keyof typeof ACTIVITY_ACTIONS];
