/**
 * Default platform settings — AviatorPass Option A (Horizon Blue & Sun Gold).
 * Palette: Horizon Blue / Aero Blue · Sun Gold / Altitude Orange · Academic Grey.
 * Typography: Stimulatio Flat pending licensed files (Space Grotesk substitute) + IBM Plex Sans.
 */

import type { PlatformSettings } from "@/types/settings";

export const DEFAULT_PLATFORM_SETTINGS: PlatformSettings = {
  general: {
    platformName: "AviatorPass",
    companyName: "AviatorPass",
    websiteUrl: "https://dubai-test.blog",
    contactEmail: "ME@ABDULAZIZALSHOAIL.COM",
    contactPhone: "",
    supportEmail: "ME@ABDULAZIZALSHOAIL.COM",
    defaultTimezone: "Asia/Kuwait",
    defaultLanguage: "en",
    dateFormat: "MMM d, yyyy",
    timeFormat: "24h",
    currency: "KWD",
    country: "KW",
    maintenanceMode: false,
    platformStatus: "online",
    primaryLocations: ["Kuwait", "Dubai"],
    footerText: "Professional Aviation Education Platform for ATPL Training.",
    socialHandle: "@ABDULAZIZ_ALSHOAIL",
    socialLinks: {
      instagram: "https://instagram.com/ABDULAZIZ_ALSHOAIL",
      twitter: "https://x.com/ABDULAZIZ_ALSHOAIL",
      linkedin: "",
      youtube: "",
    },
  },
  branding: {
    logoUrl: "/brand/logo.png",
    darkLogoUrl: "/brand/logo-dark.png",
    faviconUrl: "/brand/favicon.svg",
    loginBackgroundUrl: "/images/hero-aviation.svg",
    loginIllustrationUrl: "/images/hero-aviation.svg",
    openGraphImageUrl: "/brand/og.png",
    primaryColor: "#2E7DAA",
    secondaryColor: "#7C7B80",
    accentColor: "#DD9B30",
    typographyDisplay: "Space Grotesk",
    typographyBody: "IBM Plex Sans",
    footerInformation:
      "AviatorPass — YOUR AVIATION JOURNEY STARTS HERE. Kuwait & Dubai ATPL theory, live Zoom coaching, and exam mastery.",
    brandGuidelinesPending: false,
    colorPalettePending: false,
    typographyPending: true,
    styleGuidePending: false,
  },
  email: {
    provider: "smtp",
    smtpHost: "",
    smtpPort: 587,
    smtpUsername: "",
    smtpPassword: "",
    encryption: "tls",
    senderName: "AviatorPass",
    senderEmail: "ME@ABDULAZIZALSHOAIL.COM",
    replyToEmail: "ME@ABDULAZIZALSHOAIL.COM",
  },
  notifications: {
    emailNotifications: true,
    inAppNotifications: true,
    reminderEmails: true,
    marketingEmails: false,
    systemAlerts: true,
    classReminderOffsetsMinutes: [1440, 120],
    classReminderFifteenMinutesEnabled: true,
  },
  authentication: {
    otpExpirationMinutes: 10,
    passwordPolicyEnabled: true,
    minimumPasswordLength: 8,
    requireUppercase: true,
    requireNumber: true,
    requireSpecialChar: false,
    sessionTimeoutMinutes: 60 * 24 * 7,
    rememberMeDays: 30,
    maxLoginAttempts: 5,
    accountLockDurationMinutes: 30,
  },
  users: {
    defaultUserRole: "student",
    instructorApprovalRequired: false,
    studentApprovalRequired: false,
    emailVerificationRequired: true,
    phoneVerificationRequired: false,
  },
  security: {
    rateLimitingEnabled: true,
    rateLimitRequestsPerMinute: 60,
    ipBlockingEnabled: false,
    blockedIps: [],
    trustedDomains: ["localhost", "aviatorpass.com", "dubai-test.blog", "www.dubai-test.blog"],
    allowedFileTypes: ["image/png", "image/jpeg", "image/webp", "image/svg+xml", "application/pdf"],
    maxUploadSizeMb: 10,
    twoFactorAuthEnabled: false,
    twoFactorAuthReady: true,
    singleDeviceLogin: true,
    preventAccountSharing: true,
    deviceFingerprintingEnabled: true,
    maxConcurrentSessions: 1,
    studentOnlyDeviceLock: true,
    contentWatermarkEnabled: true,
    disableRightClickOnLearning: true,
    blockScreenshotShortcuts: true,
    deterScreenRecording: true,
    videoDownloadProtection: true,
  },
  storage: {
    provider: "local",
    supabaseBucket: "aep-uploads",
    allowedExtensions: [".png", ".jpg", ".jpeg", ".webp", ".svg", ".pdf", ".ai"],
    storageQuotaGb: 50,
    automaticCleanupEnabled: false,
    cleanupOlderThanDays: 90,
  },
  localization: {
    timezone: "Asia/Kuwait",
    country: "KW",
    language: "en",
    regionalFormatting: "en-KW",
    availableLanguages: ["en"],
    englishOnly: true,
  },
  features: {
    blog: true,
    communities: true,
    certificates: true,
    payments: true,
    zoom: true,
    advertisements: false,
    wallet: true,
    courses: true,
    calendar: true,
    ai: true,
    mockExams: true,
    cgi: true,
    schedule: true,
    installments: true,
    emailAutomation: true,
    messaging: true,
    reports: true,
    mobileApps: false,
    corporatePortal: false,
    multiTenant: false,
    aiProctoring: false,
    learningPaths: false,
    crmIntegration: false,
    erpIntegration: false,
    marketingAutomation: false,
    enterpriseSso: false,
    i18n: false,
    whiteLabel: false,
    biPredictive: false,
  },
  zoom: {
    enabled: true,
    accountEmail: "ME@ABDULAZIZALSHOAIL.COM",
    defaultWaitingRoom: true,
    defaultPasscode: true,
    defaultMeetingType: "meeting",
    credentialsConfigured: false,
  },
  courses: {
    publicDeliveryFilter: "all",
  },
  updatedAt: new Date(0).toISOString(),
  updatedBy: null,
};
