/**
 * Default platform settings — ATPL PASS.
 * Pending brand guidelines: colors/typography marked pending so they can be
 * swapped via Super Admin without code changes once the client delivers them.
 */

import type { PlatformSettings } from "@/types/settings";

export const DEFAULT_PLATFORM_SETTINGS: PlatformSettings = {
  general: {
    platformName: "ATPL PASS",
    companyName: "ATPL PASS",
    websiteUrl: "http://localhost:3000",
    contactEmail: "ME@ABDULAZIZALSHOAIL.COM",
    contactPhone: "",
    supportEmail: "ME@ABDULAZIZALSHOAIL.COM",
    defaultTimezone: "Asia/Kuwait",
    defaultLanguage: "en",
    dateFormat: "MMM d, yyyy",
    timeFormat: "24h",
    currency: "KWD",
    country: "KW",
    maintenanceMode: false,
    platformStatus: "online",
    primaryLocations: ["Kuwait", "Dubai"],
    footerText: "Professional Aviation Education Platform for ATPL Training.",
    socialHandle: "@ABDULAZIZ_ALSHOAIL",
    socialLinks: {
      instagram: "https://instagram.com/ABDULAZIZ_ALSHOAIL",
      twitter: "https://x.com/ABDULAZIZ_ALSHOAIL",
      linkedin: "",
      youtube: "",
    },
  },
  branding: {
    logoUrl: "/brand/logo.svg",
    darkLogoUrl: "/brand/logo-dark.svg",
    faviconUrl: "/brand/favicon.svg",
    loginBackgroundUrl: "/images/hero-aviation.svg",
    loginIllustrationUrl: "/images/hero-aviation.svg",
    openGraphImageUrl: "/brand/og.png",
    // Interim aviation palette until official brand guidelines arrive
    primaryColor: "#0B1F3A",
    secondaryColor: "#1E4A7A",
    accentColor: "#38BDF8",
  typographyDisplay: "Plus Jakarta Sans",
  typographyBody: "DM Sans",
    footerInformation:
      "ATPL PASS — Kuwait & Dubai. Professional Aviation Education Platform for ATPL Training.",
    brandGuidelinesPending: true,
    colorPalettePending: true,
    typographyPending: true,
    styleGuidePending: true,
  },
  email: {
    provider: "smtp",
    smtpHost: "",
    smtpPort: 587,
    smtpUsername: "",
    smtpPassword: "",
    encryption: "tls",
    senderName: "ATPL PASS",
    senderEmail: "ME@ABDULAZIZALSHOAIL.COM",
    replyToEmail: "ME@ABDULAZIZALSHOAIL.COM",
  },
  notifications: {
    emailNotifications: true,
    inAppNotifications: true,
    reminderEmails: true,
    marketingEmails: false,
    systemAlerts: true,
  },
  authentication: {
    otpExpirationMinutes: 10,
    passwordPolicyEnabled: true,
    minimumPasswordLength: 8,
    requireUppercase: true,
    requireNumber: true,
    requireSpecialChar: false,
    sessionTimeoutMinutes: 60 * 24 * 7,
    rememberMeDays: 30,
    maxLoginAttempts: 5,
    accountLockDurationMinutes: 30,
  },
  users: {
    defaultUserRole: "student",
    instructorApprovalRequired: true,
    studentApprovalRequired: false,
    emailVerificationRequired: true,
    phoneVerificationRequired: false,
  },
  security: {
    rateLimitingEnabled: true,
    rateLimitRequestsPerMinute: 60,
    ipBlockingEnabled: false,
    blockedIps: [],
    trustedDomains: ["localhost", "atplpass.com"],
    allowedFileTypes: [
      "image/png",
      "image/jpeg",
      "image/webp",
      "image/svg+xml",
      "application/pdf",
    ],
    maxUploadSizeMb: 10,
    twoFactorAuthEnabled: false,
    twoFactorAuthReady: true,
  },
  storage: {
    provider: "local",
    supabaseBucket: "aep-uploads",
    allowedExtensions: [".png", ".jpg", ".jpeg", ".webp", ".svg", ".pdf", ".ai"],
    storageQuotaGb: 50,
    automaticCleanupEnabled: false,
    cleanupOlderThanDays: 90,
  },
  localization: {
    timezone: "Asia/Kuwait",
    country: "KW",
    language: "en",
    regionalFormatting: "en-KW",
    availableLanguages: ["en"],
    englishOnly: true,
  },
  features: {
    blog: false,
    communities: false,
    certificates: false,
    payments: false,
    zoom: false,
    advertisements: false,
    wallet: false,
    courses: true,
    calendar: false,
  },
  updatedAt: new Date(0).toISOString(),
  updatedBy: null,
};
