import type { Category, Listing, UserProfile } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cars",
    name: "سيارات ومركبات",
    slug: "cars",
    icon: "🚗",
    listingCount: 1280,
    subcategories: ["سيارات مستعملة", "دراجات", "قطع غيار", "لوحات أرقام"],
  },
  {
    id: "real-estate",
    name: "عقارات",
    slug: "real-estate",
    icon: "🏠",
    listingCount: 942,
    subcategories: ["شقق للبيع", "شقق للإيجار", "فلل", "مكاتب"],
  },
  {
    id: "electronics",
    name: "إلكترونيات",
    slug: "electronics",
    icon: "💻",
    listingCount: 2140,
    subcategories: ["لابتوبات", "ألعاب", "كاميرات", "سماعات"],
  },
  {
    id: "mobiles",
    name: "موبايلات",
    slug: "mobiles",
    icon: "📱",
    listingCount: 1650,
    subcategories: ["آيفون", "سامسونج", "إكسسوارات", "أرقام مميزة"],
  },
  {
    id: "furniture",
    name: "أثاث ومنزل",
    slug: "furniture",
    icon: "🛋️",
    listingCount: 768,
    subcategories: ["غرف نوم", "كنب", "مطابخ", "ديكور"],
  },
  {
    id: "jobs",
    name: "وظائف وخدمات",
    slug: "jobs",
    icon: "💼",
    listingCount: 530,
    subcategories: ["وظائف شاغرة", "خدمات منزلية", "تصميم", "نقل"],
  },
  {
    id: "fashion",
    name: "أزياء وإكسسوارات",
    slug: "fashion",
    icon: "⌚",
    listingCount: 615,
    subcategories: ["ساعات", "حقائب", "ملابس", "عطور"],
  },
  {
    id: "pets",
    name: "الحيوانات",
    slug: "pets",
    icon: "🐾",
    listingCount: 284,
    subcategories: ["قطط", "كلاب", "طيور", "مستلزمات"],
  },
  {
    id: "services",
    name: "الخدمات",
    slug: "services",
    icon: "🛠️",
    listingCount: 720,
    subcategories: ["صيانة", "تنظيف", "نقل", "تصميم"],
  },
  {
    id: "kids",
    name: "الأطفال",
    slug: "kids",
    icon: "🧸",
    listingCount: 340,
    subcategories: ["عربات أطفال", "ألعاب", "ملابس أطفال", "مستلزمات"],
  },
  {
    id: "books",
    name: "الكتب",
    slug: "books",
    icon: "📚",
    listingCount: 190,
    subcategories: ["كتب عربية", "كتب جامعية", "روايات", "مناهج"],
  },
  {
    id: "sports",
    name: "الرياضة",
    slug: "sports",
    icon: "⚽",
    listingCount: 410,
    subcategories: ["معدات رياضية", "دراجات", "لياقة", "تخييم"],
  },
  {
    id: "food",
    name: "الطعام",
    slug: "food",
    icon: "🍽️",
    listingCount: 260,
    subcategories: ["أكلات منزلية", "تمور", "حلويات", "ضيافة"],
  },
];

export const mockCurrentUser: UserProfile = {
  id: "user-current",
  fullName: "أحمد المنصوري",
  email: "ahmed@example.com",
  phone: "0501234567",
  city: "دبي",
  accountType: "seller",
  isVerified: false,
  joinedAt: "2026-01-15",
};

export const mockListings: Listing[] = [
  {
    id: "listing-001",
    title: "تويوتا لاند كروزر 2022 بحالة ممتازة",
    slug: "toyota-land-cruiser-2022",
    description:
      "سيارة خليجية نظيفة مع سجل صيانة كامل، جاهزة للفحص والتحويل الفوري.",
    categoryId: "cars",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 238000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: true,
    views: 1240,
    seller: {
      id: "seller-1",
      name: "معرض النخبة",
      rating: 4.9,
    },
    imageTone: "gold",
  },
  {
    id: "listing-002",
    title: "آيفون 15 برو ماكس 256 جيجابايت",
    slug: "iphone-15-pro-max-256gb",
    description:
      "جهاز جديد بضمان محلي، اللون تيتانيوم طبيعي مع كامل الملحقات الأصلية.",
    categoryId: "mobiles",
    city: "أبوظبي",
    country: "الإمارات العربية المتحدة",
    price: 3950,
    currency: "AED",
    condition: "new",
    status: "active",
    isFeatured: true,
    views: 980,
    seller: {
      id: "seller-2",
      name: "سارة للتقنية",
      rating: 4.8,
    },
    imageTone: "sky",
  },
  {
    id: "listing-003",
    title: "شقة غرفة وصالة بإطلالة بحرية",
    slug: "sea-view-one-bedroom-apartment",
    description:
      "شقة جاهزة للسكن في برج حديث، قريبة من الخدمات وتناسب الاستثمار أو السكن.",
    categoryId: "real-estate",
    city: "الشارقة",
    country: "الإمارات العربية المتحدة",
    price: 680000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: true,
    views: 760,
    seller: {
      id: "seller-3",
      name: "دار الخليج العقارية",
      rating: 4.7,
    },
    imageTone: "amber",
  },
  {
    id: "listing-004",
    title: "طقم كنب فاخر مع طاولة وسط",
    slug: "luxury-sofa-set",
    description:
      "طقم كنب بحالة ممتازة واستخدام خفيف، مناسب للمجالس وغرف المعيشة.",
    categoryId: "furniture",
    city: "عجمان",
    country: "الإمارات العربية المتحدة",
    price: 4200,
    currency: "AED",
    condition: "used",
    status: "active",
    isFeatured: true,
    views: 420,
    seller: {
      id: "seller-4",
      name: "بيت الأناقة",
      rating: 4.6,
    },
    imageTone: "rose",
  },
  {
    id: "listing-005",
    title: "مرسيدس C300 موديل 2021",
    slug: "mercedes-c300-2021",
    description:
      "سيارة وارد وكالة بحالة ممتازة، مواصفات عالية وعداد منخفض.",
    categoryId: "cars",
    city: "أبوظبي",
    country: "الإمارات العربية المتحدة",
    price: 146000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: false,
    views: 360,
    seller: {
      id: "seller-5",
      name: "أوتو الإمارات",
      rating: 4.7,
    },
    imageTone: "slate",
  },
  {
    id: "listing-006",
    title: "لابتوب ماك بوك برو M3",
    slug: "macbook-pro-m3",
    description:
      "لابتوب احترافي بذاكرة 18 جيجابايت وتخزين 512 جيجابايت، استخدام شهرين.",
    categoryId: "electronics",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 8200,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: false,
    views: 295,
    seller: {
      id: "seller-2",
      name: "سارة للتقنية",
      rating: 4.8,
    },
    imageTone: "sky",
  },
  {
    id: "listing-007",
    title: "خدمة تصوير منتجات للمتاجر",
    slug: "product-photography-service",
    description:
      "جلسات تصوير احترافية للمنتجات مع تحرير صور جاهزة للمتاجر والإعلانات.",
    categoryId: "services",
    city: "الشارقة",
    country: "الإمارات العربية المتحدة",
    price: 750,
    currency: "AED",
    condition: "new",
    status: "active",
    isFeatured: false,
    views: 188,
    seller: {
      id: "seller-6",
      name: "استوديو لقطة",
      rating: 4.9,
    },
    imageTone: "gold",
  },
  {
    id: "listing-008",
    title: "ساعة رولكس ديت جست أصلية",
    slug: "rolex-datejust-original",
    description:
      "ساعة أصلية مع العلبة والأوراق، متاحة للفحص في متجر موثوق.",
    categoryId: "fashion",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 38500,
    currency: "AED",
    condition: "used",
    status: "active",
    isFeatured: false,
    views: 540,
    seller: {
      id: "seller-7",
      name: "زمن الفخامة",
      rating: 4.6,
    },
    imageTone: "amber",
  },
  {
    id: "listing-009",
    title: "فرصة عمل لمندوب مبيعات",
    slug: "sales-representative-job",
    description:
      "شركة محلية تبحث عن مندوب مبيعات بخبرة في السوق الإماراتي وعمولات مجزية.",
    categoryId: "jobs",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 5000,
    currency: "AED",
    condition: "new",
    status: "active",
    isFeatured: false,
    views: 142,
    seller: {
      id: "seller-8",
      name: "الخليج للتوظيف",
      rating: 4.5,
    },
    imageTone: "gold",
  },
  {
    id: "listing-010",
    title: "قطة شيرازي مع مستلزماتها",
    slug: "persian-cat-with-supplies",
    description:
      "قطة أليفة مطعمة ومعها مستلزمات كاملة، مناسبة لعائلة تهتم بالحيوانات.",
    categoryId: "pets",
    city: "الشارقة",
    country: "الإمارات العربية المتحدة",
    price: 1200,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: false,
    views: 210,
    seller: {
      id: "seller-9",
      name: "مركز الرفق",
      rating: 4.8,
    },
    imageTone: "rose",
  },
];

export const mockUserListings: Listing[] = [
  {
    id: "user-listing-001",
    title: "نيسان باترول 2020 للبيع",
    slug: "my-nissan-patrol-2020",
    description:
      "سيارة عائلية بحالة ممتازة، صيانة وكالة، جاهزة للفحص في دبي.",
    categoryId: "cars",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 168000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: false,
    views: 89,
    seller: {
      id: "user-current",
      name: "أحمد المنصوري",
      rating: 4.8,
    },
    imageTone: "gold",
  },
  {
    id: "user-listing-002",
    title: "كاميرا كانون احترافية",
    slug: "my-canon-camera",
    description:
      "كاميرا مع عدسة أساسية وحقيبة، مناسبة للتصوير الاحترافي والهواة.",
    categoryId: "electronics",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 3200,
    currency: "AED",
    condition: "used",
    status: "pending_review",
    isFeatured: false,
    views: 0,
    seller: {
      id: "user-current",
      name: "أحمد المنصوري",
      rating: 4.8,
    },
    imageTone: "sky",
  },
  {
    id: "user-listing-003",
    title: "طاولة طعام خشب طبيعي",
    slug: "my-wooden-dining-table",
    description:
      "مسودة إعلان لطاولة طعام ستة كراسي، بحاجة لإضافة صور قبل النشر.",
    categoryId: "furniture",
    city: "الشارقة",
    country: "الإمارات العربية المتحدة",
    price: 1800,
    currency: "AED",
    condition: "excellent",
    status: "draft",
    isFeatured: false,
    views: 0,
    seller: {
      id: "user-current",
      name: "أحمد المنصوري",
      rating: 4.8,
    },
    imageTone: "amber",
  },
  {
    id: "user-listing-004",
    title: "شقة استوديو للإيجار الشهري",
    slug: "my-studio-apartment-rent",
    description:
      "إعلان منتهي لشقة استوديو مفروشة، يمكن إعادة تنشيطه بعد تحديث السعر.",
    categoryId: "real-estate",
    city: "عجمان",
    country: "الإمارات العربية المتحدة",
    price: 3200,
    currency: "AED",
    condition: "excellent",
    status: "expired",
    isFeatured: false,
    views: 330,
    seller: {
      id: "user-current",
      name: "أحمد المنصوري",
      rating: 4.8,
    },
    imageTone: "rose",
  },
  {
    id: "user-listing-005",
    title: "ساعة ذكية مستعملة",
    slug: "my-used-smart-watch",
    description:
      "إعلان مرفوض مؤقتاً بسبب نقص تفاصيل الحالة والصور، جاهز للتعديل.",
    categoryId: "fashion",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 450,
    currency: "AED",
    condition: "used",
    status: "rejected",
    isFeatured: false,
    views: 0,
    seller: {
      id: "user-current",
      name: "أحمد المنصوري",
      rating: 4.8,
    },
    imageTone: "slate",
  },
];
