import type { Category, Listing } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cars",
    name: "سيارات ومركبات",
    slug: "cars",
    icon: "🚗",
    listingCount: 1280,
    subcategories: ["سيارات مستعملة", "دراجات", "قطع غيار", "لوحات أرقام"],
  },
  {
    id: "real-estate",
    name: "عقارات",
    slug: "real-estate",
    icon: "🏠",
    listingCount: 942,
    subcategories: ["شقق للبيع", "شقق للإيجار", "فلل", "مكاتب"],
  },
  {
    id: "electronics",
    name: "إلكترونيات",
    slug: "electronics",
    icon: "📱",
    listingCount: 2140,
    subcategories: ["هواتف", "لابتوبات", "ألعاب", "كاميرات"],
  },
  {
    id: "furniture",
    name: "أثاث ومنزل",
    slug: "furniture",
    icon: "🛋️",
    listingCount: 768,
    subcategories: ["غرف نوم", "كنب", "مطابخ", "ديكور"],
  },
  {
    id: "jobs",
    name: "وظائف وخدمات",
    slug: "jobs",
    icon: "💼",
    listingCount: 530,
    subcategories: ["وظائف شاغرة", "خدمات منزلية", "تصميم", "نقل"],
  },
  {
    id: "fashion",
    name: "أزياء وإكسسوارات",
    slug: "fashion",
    icon: "⌚",
    listingCount: 615,
    subcategories: ["ساعات", "حقائب", "ملابس", "عطور"],
  },
];

export const mockListings: Listing[] = [
  {
    id: "listing-001",
    title: "تويوتا لاند كروزر 2022 بحالة ممتازة",
    slug: "toyota-land-cruiser-2022",
    description:
      "سيارة خليجية نظيفة مع سجل صيانة كامل، جاهزة للفحص والتحويل الفوري.",
    categoryId: "cars",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 238000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-1",
      name: "معرض النخبة",
      rating: 4.9,
    },
    imageTone: "emerald",
  },
  {
    id: "listing-002",
    title: "آيفون 15 برو ماكس 256 جيجابايت",
    slug: "iphone-15-pro-max-256gb",
    description:
      "جهاز جديد بضمان محلي، اللون تيتانيوم طبيعي مع كامل الملحقات الأصلية.",
    categoryId: "electronics",
    city: "أبوظبي",
    country: "الإمارات العربية المتحدة",
    price: 3950,
    currency: "AED",
    condition: "new",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-2",
      name: "سارة للتقنية",
      rating: 4.8,
    },
    imageTone: "sky",
  },
  {
    id: "listing-003",
    title: "شقة غرفة وصالة بإطلالة بحرية",
    slug: "sea-view-one-bedroom-apartment",
    description:
      "شقة جاهزة للسكن في برج حديث، قريبة من الخدمات وتناسب الاستثمار أو السكن.",
    categoryId: "real-estate",
    city: "الشارقة",
    country: "الإمارات العربية المتحدة",
    price: 680000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-3",
      name: "دار الخليج العقارية",
      rating: 4.7,
    },
    imageTone: "amber",
  },
  {
    id: "listing-004",
    title: "طقم كنب فاخر مع طاولة وسط",
    slug: "luxury-sofa-set",
    description:
      "طقم كنب بحالة ممتازة واستخدام خفيف، مناسب للمجالس وغرف المعيشة.",
    categoryId: "furniture",
    city: "عجمان",
    country: "الإمارات العربية المتحدة",
    price: 4200,
    currency: "AED",
    condition: "used",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-4",
      name: "بيت الأناقة",
      rating: 4.6,
    },
    imageTone: "rose",
  },
  {
    id: "listing-005",
    title: "مرسيدس C300 موديل 2021",
    slug: "mercedes-c300-2021",
    description:
      "سيارة وارد وكالة بحالة ممتازة، مواصفات عالية وعداد منخفض.",
    categoryId: "cars",
    city: "أبوظبي",
    country: "الإمارات العربية المتحدة",
    price: 146000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: false,
    seller: {
      id: "seller-5",
      name: "أوتو الإمارات",
      rating: 4.7,
    },
    imageTone: "slate",
  },
  {
    id: "listing-006",
    title: "لابتوب ماك بوك برو M3",
    slug: "macbook-pro-m3",
    description:
      "لابتوب احترافي بذاكرة 18 جيجابايت وتخزين 512 جيجابايت، استخدام شهرين.",
    categoryId: "electronics",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 8200,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: false,
    seller: {
      id: "seller-2",
      name: "سارة للتقنية",
      rating: 4.8,
    },
    imageTone: "sky",
  },
  {
    id: "listing-007",
    title: "خدمة تصوير منتجات للمتاجر",
    slug: "product-photography-service",
    description:
      "جلسات تصوير احترافية للمنتجات مع تحرير صور جاهزة للمتاجر والإعلانات.",
    categoryId: "jobs",
    city: "الشارقة",
    country: "الإمارات العربية المتحدة",
    price: 750,
    currency: "AED",
    condition: "new",
    status: "active",
    isFeatured: false,
    seller: {
      id: "seller-6",
      name: "استوديو لقطة",
      rating: 4.9,
    },
    imageTone: "emerald",
  },
  {
    id: "listing-008",
    title: "ساعة رولكس ديت جست أصلية",
    slug: "rolex-datejust-original",
    description:
      "ساعة أصلية مع العلبة والأوراق، متاحة للفحص في متجر موثوق.",
    categoryId: "fashion",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    price: 38500,
    currency: "AED",
    condition: "used",
    status: "active",
    isFeatured: false,
    seller: {
      id: "seller-7",
      name: "زمن الفخامة",
      rating: 4.6,
    },
    imageTone: "amber",
  },
];
