import type { Category, Listing } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cars",
    name: "سيارات ومركبات",
    slug: "cars",
    icon: "🚗",
    listingCount: 1280,
    subcategories: ["سيارات مستعملة", "دراجات", "قطع غيار", "لوحات أرقام"],
  },
  {
    id: "real-estate",
    name: "عقارات",
    slug: "real-estate",
    icon: "🏠",
    listingCount: 942,
    subcategories: ["شقق للبيع", "شقق للإيجار", "فلل", "مكاتب"],
  },
  {
    id: "electronics",
    name: "إلكترونيات",
    slug: "electronics",
    icon: "📱",
    listingCount: 2140,
    subcategories: ["هواتف", "لابتوبات", "ألعاب", "كاميرات"],
  },
  {
    id: "furniture",
    name: "أثاث ومنزل",
    slug: "furniture",
    icon: "🛋️",
    listingCount: 768,
    subcategories: ["غرف نوم", "كنب", "مطابخ", "ديكور"],
  },
  {
    id: "jobs",
    name: "وظائف وخدمات",
    slug: "jobs",
    icon: "💼",
    listingCount: 530,
    subcategories: ["وظائف شاغرة", "خدمات منزلية", "تصميم", "نقل"],
  },
  {
    id: "fashion",
    name: "أزياء وإكسسوارات",
    slug: "fashion",
    icon: "⌚",
    listingCount: 615,
    subcategories: ["ساعات", "حقائب", "ملابس", "عطور"],
  },
];

export const mockListings: Listing[] = [
  {
    id: "listing-001",
    title: "تويوتا لاند كروزر 2022 بحالة ممتازة",
    slug: "toyota-land-cruiser-2022",
    categoryId: "cars",
    city: "دبي",
    country: "الإمارات",
    price: 238000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-1",
      name: "معرض النخبة",
      rating: 4.9,
    },
    imageTone: "emerald",
  },
  {
    id: "listing-002",
    title: "آيفون 15 برو ماكس 256 جيجابايت",
    slug: "iphone-15-pro-max-256gb",
    categoryId: "electronics",
    city: "أبوظبي",
    country: "الإمارات",
    price: 3950,
    currency: "AED",
    condition: "new",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-2",
      name: "سارة للتقنية",
      rating: 4.8,
    },
    imageTone: "sky",
  },
  {
    id: "listing-003",
    title: "شقة غرفة وصالة بإطلالة بحرية",
    slug: "sea-view-one-bedroom-apartment",
    categoryId: "real-estate",
    city: "الشارقة",
    country: "الإمارات",
    price: 680000,
    currency: "AED",
    condition: "excellent",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-3",
      name: "دار الخليج العقارية",
      rating: 4.7,
    },
    imageTone: "amber",
  },
  {
    id: "listing-004",
    title: "طقم كنب فاخر مع طاولة وسط",
    slug: "luxury-sofa-set",
    categoryId: "furniture",
    city: "عجمان",
    country: "الإمارات",
    price: 4200,
    currency: "AED",
    condition: "used",
    status: "active",
    isFeatured: true,
    seller: {
      id: "seller-4",
      name: "بيت الأناقة",
      rating: 4.6,
    },
    imageTone: "rose",
  },
];
